# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: szaghban <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/04 15:17:42 by szaghban          #+#    #+#              #
#    Updated: 2018/11/04 16:40:38 by szaghban         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Container for C projects

FROM debian

MAINTAINER szaghban <szaghban@student.42.fr>

RUN apt-get update && apt-get upgrade -y && apt-get install -y build-essential git vim

# docker build -t b00 .
# docker run --rm -ti b00
